name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master # Поддерживает запуск при пуше как в ветку main, так и в master

  # Позволяет запускать деплой вручную из вкладки Actions на GitHub
  workflow_dispatch:

# Установка необходимых разрешений для деплоя на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Предотвращает одновременный запуск нескольких деплоев
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 18
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          # Указываем переменную окружения, чтобы Vite знал, что это сборка GitHub Actions
          GITHUB_ACTIONS: true
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Указываем папку, куда Vite компилирует сжатый клиентский код
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
